// ─── Texas enrichment overlay — HUMAN-VERIFIED facts (July 16, 2026) ───────────
// Sources: Texas statutes (statute links come scraped per board). Texas runs in
// INVENTORY MODE — no central vacancy list; applications accepted year-round.
// Depth expansion July 20, 2026: +8 statute-cited boards (health, housing,
// education, environment, finance oversight).
export const ENRICHMENTS = {
  "Behavioral Health Executive Council, Texas": {
    totalSeats: 9, domain: "health",
    constituent: "Texans served by licensed behavioral health professionals",
    mandate: "Oversees licensing and enforcement for psychologists, counselors, social workers, and marriage & family therapists. Nine members — eight appointed by member boards, one governor-appointed public member (Occ. Code 507.051).",
    seatSource: "https://texas.public.law/statutes/tex._occ._code_section_507.051",
    criticalNote: "1 of 9 seats is governor-appointed",
  },
  "Higher Education Coordinating Board, Texas": {
    totalSeats: 9, domain: "education",
    constituent: "Texas college students & institutions",
    mandate: "Coordinates Texas public higher education strategy, funding formulas, and program approval. Nine members appointed by the Governor with Senate consent for six-year terms (Educ. Code 61.022).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/ED/htm/ED.61.htm",
  },
  "Diabetes Council, Texas": {
    totalSeats: 16, domain: "health",
    constituent: "Texans living with or at risk of diabetes",
    mandate: "Advises the legislature on diabetes policy and administers the state diabetes plan. Sixteen members — eleven governor-appointed citizens plus five agency representatives (Health & Safety Code 103.002).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/HS/htm/HS.103.htm",
    criticalNote: "11 of 16 seats are governor-appointed",
  },
  "Alzheimer's Disease and Related Disorders, Texas Council on": {
    totalSeats: 15, domain: "health",
    constituent: "Texans affected by Alzheimer's & related disorders",
    mandate: "Guides the state plan on Alzheimer's disease. Fifteen members — four each appointed by the Governor, Lt. Governor, and Speaker, plus three agency representatives (Health & Safety Code ch. 101).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/HS/htm/HS.101.htm",
    criticalNote: "4 of 15 seats are governor-appointed",
  },
  "Cancer Prevention and Research Institute of Texas Oversight Committee": {
    totalSeats: 9, domain: "health",
    constituent: "Texans affected by cancer · multibillion-dollar research & prevention program",
    mandate: "Governs the Cancer Prevention and Research Institute of Texas, awarding grants for cancer research and prevention statewide. Nine members — three each appointed by the Governor, Lt. Governor, and Speaker (Health & Safety Code ch. 102).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/HS/htm/HS.102.htm",
    criticalNote: "3 of 9 seats are governor-appointed",
  },
  "Opioid Abatement Fund Council, Texas": {
    totalSeats: 13, domain: "health",
    constituent: "Texans affected by the opioid crisis · settlement-fund allocation",
    mandate: "Directs the allocation of Texas's opioid settlement funds toward abatement across the state. Thirteen appointed members representing affected regions and professions, with the Comptroller as nonvoting presiding officer (Gov. Code 403.503).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/GV/htm/GV.403.htm",
    criticalNote: "Comptroller serves as nonvoting presiding officer",
  },
  "Housing and Community Affairs, Texas Department of": {
    totalSeats: 7, domain: "housing",
    constituent: "Low-income Texans · state housing & community programs",
    mandate: "Governs Texas's housing finance and community affairs programs, including the low-income housing tax credit. Seven members appointed by the Governor with the advice and consent of the Senate (Gov. Code 2306.024).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/GV/htm/GV.2306.htm",
  },
  "Affordable Housing Corporation Board of Directors, Texas State": {
    totalSeats: 5, domain: "housing",
    constituent: "Low- and moderate-income Texans seeking affordable housing",
    mandate: "Sets policy for the Texas State Affordable Housing Corporation's homeownership, lending, and development programs. Five members appointed by the Governor with the advice and consent of the Senate (Gov. Code 2306.554).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/GV/htm/GV.2306.htm",
  },
  "School Land Board": {
    totalSeats: 5, domain: "environment",
    constituent: "Texas public schools · Permanent School Fund real-asset value",
    mandate: "Manages the real-asset investments and state lands that help fund the Permanent School Fund for Texas public education. Five members — the Land Commissioner as chair plus four citizens appointed by the Governor (Nat. Resources Code 32.012).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/NR/htm/NR.32.htm",
    criticalNote: "4 of 5 seats are governor-appointed",
  },
  "Pension Review Board, State": {
    totalSeats: 9, domain: "justice",
    constituent: "Texas public employees & retirees · pension-fund solvency",
    mandate: "Oversees the actuarial soundness and transparency of all Texas public retirement systems. Nine members appointed by the Governor with the advice and consent of the Senate (Gov. Code 801.102).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/GV/htm/GV.801.htm",
  },
  "Permanent School Fund Corporation Board of Directors, Texas": {
    totalSeats: 9, domain: "education",
    constituent: "Texas public school students · multibillion-dollar education endowment",
    mandate: "Manages the Permanent School Fund endowment that supports Texas public schools. Nine members — five appointed by the State Board of Education, the Land Commissioner, one General Land Office appointee, and two governor-appointed investment experts (Educ. Code 43.053).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/ED/htm/ED.43.htm",
    criticalNote: "2 of 9 seats are governor-appointed",
  },
  "Employees Retirement System of Texas Board of Trustees": {
    totalSeats: 6, domain: "equity",
    constituent: "Texas state employees & retirees · retirement and benefits",
    mandate: "Administers retirement, insurance, and benefit programs for Texas state employees and retirees. Six trustees — three appointed (by the Governor, Speaker, and Chief Justice) and three elected by members (Gov. Code 815.002).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/GV/htm/GV.815.htm",
    criticalNote: "1 of 6 seats is governor-appointed",
  },
  "Medical Board, Texas": {
    totalSeats: 19, domain: "health",
    constituent: "Texas patients & licensed physicians",
    mandate: "Licenses and disciplines Texas's physicians. Nineteen members appointed by the Governor with Senate consent — twelve physicians (nine M.D., three D.O.) and seven public members (Tex. Occ. Code 152.002).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/OC/htm/OC.152.htm",
  },
  "Nursing, Texas Board of": {
    totalSeats: 15, domain: "health",
    constituent: "Texas patients & licensed nurses",
    mandate: "Licenses and regulates Texas's nurses. Fifteen members appointed by the Governor with Senate consent — nurse members (RN, APRN, LVN), nurse-faculty, and public members (Tex. Occ. Code 301.051; expanded from 13 in 2023).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/OC/htm/OC.301.htm",
  },
  "Pharmacy, Texas State Board of": {
    totalSeats: 11, domain: "health",
    constituent: "Texas patients & licensed pharmacists · drug safety",
    mandate: "Licenses pharmacists and regulates pharmacy practice in Texas. Eleven members appointed by the Governor with Senate consent — seven pharmacists, one pharmacy technician, and three public members (Tex. Occ. Code 555).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/OC/htm/OC.555.htm",
  },
  "Dental Examiners, State Board of": {
    totalSeats: 11, domain: "health",
    constituent: "Texas dental patients & licensed dentists/hygienists",
    mandate: "Licenses and disciplines Texas's dentists and dental hygienists. Eleven members appointed by the Governor with Senate consent — six dentists, three hygienists, and two public members (Tex. Occ. Code 254.001).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/OC/htm/OC.254.htm",
  },
  "Optometry Board, Texas": {
    totalSeats: 9, domain: "health",
    constituent: "Texas eye-care patients & licensed optometrists",
    mandate: "Licenses and regulates Texas's optometrists. Nine members appointed by the Governor with Senate consent — six optometrists and three public members (Tex. Occ. Code 351.051).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/OC/htm/OC.351.htm",
  },
  "Chiropractic Examiners, Texas Board of": {
    totalSeats: 9, domain: "health",
    constituent: "Texas chiropractic patients & licensees",
    mandate: "Licenses and disciplines Texas's chiropractors. Nine members appointed by the Governor with Senate consent — six chiropractors and three public members (Tex. Occ. Code 201.051).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/OC/htm/OC.201.htm",
  },
  "Physical Therapy Examiners, Texas Board of": {
    totalSeats: 9, domain: "health",
    constituent: "Texas patients & licensed physical therapists",
    mandate: "Licenses and regulates Texas's physical therapists and PT assistants. Nine members appointed by the Governor with Senate consent — six physical therapists and three public members (Tex. Occ. Code 453.051).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/OC/htm/OC.453.htm",
  },
  "Veterinary Medical Examiners, State Board of": {
    totalSeats: 9, domain: "health",
    constituent: "Texas animal owners & licensed veterinarians",
    mandate: "Licenses and disciplines Texas's veterinarians and veterinary technicians. Nine members appointed by the Governor with Senate consent — veterinarians, a veterinary technician, and public members (Tex. Occ. Code 801.051).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/OC/htm/OC.801.htm",
  },
  "Accountancy, Texas State Board of Public": {
    totalSeats: 15, domain: "justice",
    constituent: "Texas businesses & licensed CPAs · audit integrity",
    mandate: "Licenses and disciplines Texas's certified public accountants. Fifteen members appointed by the Governor with Senate consent — ten CPAs and five public members (Tex. Occ. Code 901.051).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/OC/htm/OC.901.htm",
  },
  "Real Estate Commission, Texas": {
    totalSeats: 9, domain: "housing",
    constituent: "Texas home buyers & licensed real estate brokers",
    mandate: "Licenses and regulates Texas's real estate brokers and sales agents. Nine members appointed by the Governor with Senate consent — six brokers and three public members (Tex. Occ. Code 1101.051).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/OC/htm/OC.1101.htm",
  },
  "Parks and Wildlife Commission": {
    totalSeats: 9, domain: "environment",
    constituent: "Texas hunters, anglers, state parks & wildlife",
    mandate: "Governs the Texas Parks and Wildlife Department — hunting, fishing, and state parks. Nine members appointed by the Governor with Senate consent, staggered six-year terms (Tex. Parks & Wild. Code 11.0111).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/PW/htm/PW.11.htm",
  },
  "Public Utility Commission of Texas": {
    totalSeats: 5, domain: "justice",
    constituent: "Every Texas utility ratepayer · electric, water, telecom",
    mandate: "Regulates Texas's electric, water, and telecommunications utilities and oversees the state's power grid. Five commissioners appointed by the Governor with Senate consent, six-year staggered terms (Tex. Util. Code 12.051).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/UT/htm/UT.12.htm",
  },
  "Transportation Commission, Texas": {
    totalSeats: 5, domain: "environment",
    constituent: "Texas travelers & the statewide highway system",
    mandate: "Governs the Texas Department of Transportation — highways, funding, and major projects. Five members, six-year terms: the Governor appoints four (one from the House Speaker's list) and the Lieutenant Governor appoints one (Tex. Transp. Code 201.051).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/TN/htm/TN.201.htm",
    criticalNote: "4 of 5 seats are governor-appointed (1 by the Lieutenant Governor)",
  },
  "Environmental Quality, Texas Commission on": {
    totalSeats: 3, domain: "environment",
    constituent: "All Texans · air, water & waste permitting",
    mandate: "Texas's environmental regulator — air, water, and waste permitting and enforcement. Three commissioners appointed by the Governor with Senate consent, six-year staggered terms (Tex. Water Code 5.052).",
    seatSource: "https://statutes.capitol.texas.gov/Docs/WA/htm/WA.5.htm",
  },
};
